# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170824_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='code',
            field=models.CharField(max_length=100, verbose_name='验证码'),
        ),
    ]
